### PR TITLE
extend compatibility section in README

### PR DESCRIPTION
**Pull request by AiyionPrime**
I'm successfully using this repo on three openwrt 21.02.1 devices.
My playbook doesn't cover everything, but maybe someone can extend the modules successfully used.

This PR adds 21.02 to the compatibility section in the readme file.

- [x] command
- [x] copy
- [x] fetch (implicit)
- [x] file
- [x] lineinfile
- [x] nohup
- [x] opkg
- [x] ping
- [x] service
- [x] setup
- [x] shell (implicit)
- [x] slurp
- [x] stat
- [x] sysctl
- [x] template (implicit)
- [x] uci (new)
- [x] wait_for_connection (implicit)

### CODE REVIEW

**Comment by elduds** [comment]
I've had no issues on two 21.02* devices

**Comment by AiyionPrime** [comment]
@elduds Thats nice to hear; mind to share which of the above modules your playbook uses?

**Comment by sseide** [comment]
updated multiple devices from 19.07 to 21.02.1 with it and work flawlessy (Thanks!)

used modules:
* command
* copy
* lineinfile
* opkg
* service
* template
* uci (commit / section / get / add_list / set / reboot)

**Comment by AiyionPrime** [comment]
Updated the list, thank you.

**Comment by gekmihesg** [comment]
Thanks for testing, I didn't really come around to do so by now.
When using `fetch` it really uses `slurp` [internally](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/fetch.py#L111).
For `wait_for_connection`, the `ping` module is [used](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/wait_for_connection.py#L91).
Also, if you run your playbook with `gather_facts: yes`, the `setup` module is invoked and unless you specify `openwrt_install_recommended_packages: no`, the `stat` module is [used](https://github.com/gekmihesg/ansible-openwrt/blob/master/tasks/packages.yml#L3).

**Comment by AiyionPrime** [comment]
Thanks for the insight; updated again. I'll see whether I get a demo playbook running that tests the remaining this afternoon.

**Comment by elduds** [comment]
> @elduds That's nice to hear; mind to share which of the above modules your playbook uses?

I'm using
- uci
- opkg
- service
- copy
- sysctl

**Comment by AiyionPrime** [comment]
That leaves us with `file`, thanks!

**Comment by j0ju** [comment]
I can confirm that file works for creating and removing files, directories and links.

**Comment by AiyionPrime** [comment]
@gekmihesg, then this is fianlly ready to merge.

**Pull request merged**
